#!/bin/sh
COURSIER_URL=https://raw.githubusercontent.com/alexarchambault/coursier/v1.0.0-M12/coursier
test -e ~/.coursier/cr || (mkdir -p ~/.coursier && curl -s --output ~/.coursier/cr $COURSIER_URL && chmod +x ~/.coursier/cr)
#~/.coursier/cr launch \
#  -r http://amp:P0weramp@amparchiva.int.ihrdev.com/repository/snapshots \
#  com.joprice:prs_2.11:0.0.1-SNAPSHOT-assembly \
#  -M prs.Main
~/.coursier/cr bootstrap \
  -r http://amp:P0weramp@amparchiva.int.ihrdev.com/repository/snapshots \
  -f -o prs \
  -M prs.Main \
  --download-dir $HOME/.prs/jars \
  com.joprice:prs_2.11:0.0.1-SNAPSHOT
